server:
  port: 2201

spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/sg_security?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # redis配置
  redis:
    host: localhost
    port: 6379
    #password: 123456