server:
  port: 2201

spring:
  cache:
    type: generic

  datasource:
    db1: # 数据源1
      jdbc-url: jdbc:mysql://localhost:3306/my_test?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    db2: # 数据源2
      jdbc-url: jdbc:mysql://localhost:3306/world?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  durid:
    initial-size: 1
    max-active: 20
    min-idle: 1
    max-wait: 60000
autoconfigure:
  exclude:  com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure # 去除druid配置


    # redis配置
  redis:
    host: localhost
    port: 6379
    #password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        #最大空闲数
        max-idle: 8
        min-idle: 0

    # 连接超时时间
    timeout: 30000

  data:
    solr:
      host: http://127.0.0.1:8983/solr